import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className="">
        <div className="h-screen bg-gray-100 h-full flex flex-col">
          <nav className=" bg-sky-300">
            navbar
          </nav>
          <main className="flex-grow">
          {children}
          </main>          
          <footer className="bg-blue-400 text-xs flex gap-6 items-center justify-center mb-0">
            Diseñado por Joluro Soft - Todos los derechos reservados
          </footer>
        </div>
      </body>
    </html>
  );
}
